import React from 'react';
import { Database, Scale, Wallet } from 'lucide-react';
import { buildDailyJournalReport, DailyJournalDimension } from '../../../lib/dailyJournalReport';
import { cn } from '../../../lib/utils';
import { formatEgpNumber, formatQuantity, formatWeight } from '../../../lib/formatting';
import { buildDailyJournalSmartDashboard } from '../../../lib/dailyJournalSmartDashboard';

const amount = (value: number, dimension: DailyJournalDimension) => dimension === 'cash' ? formatEgpNumber(value) : dimension === 'quantity' ? formatQuantity(value, 3) : formatWeight(value, 2);

export const CashClosingCard = ({ cash }: { cash: ReturnType<typeof buildDailyJournalSmartDashboard>['cash'] }) => <section className="rounded-3xl border border-[#6a9e6a66] bg-[#0e1018] p-5 shadow-2xl" dir="rtl"><h3 className="flex items-center gap-2 text-sm font-black text-[#6a9e6a]"><Wallet className="h-4 w-4" />رصيد وإقفال الخزنة</h3><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-5"><Metric label="رصيد أول اليوم" value={formatEgpNumber(cash.opening)} /><Metric label="إجمالي الداخل النقدي" value={formatEgpNumber(cash.cashIn)} /><Metric label="الرصيد + الداخل" value={formatEgpNumber(cash.availableBeforeOut)} /><Metric label="إجمالي الخارج النقدي" value={formatEgpNumber(cash.cashOut)} /><Metric label="رصيد آخر اليوم" value={formatEgpNumber(cash.closing)} strong /></div></section>;

export const SmartDashboard = ({ report }: { report: ReturnType<typeof buildDailyJournalSmartDashboard> }) => { const money = (v: number | null) => v === null ? 'غير متاح' : `${formatEgpNumber(v)} ج/جم E21`; const row = (label: string, w: ReturnType<typeof buildDailyJournalSmartDashboard>['gold']['sales']['today']) => <div className="grid grid-cols-4 gap-2 rounded-xl bg-[#080a0f] p-2 text-[10px]"><span>{label}</span><span>{formatWeight(w.e21, 2)} E21</span><span>{formatEgpNumber(w.egp)} ج</span><span>{money(w.average)}</span></div>; const secondary = [
    `التجار — ذهب مستلم: ${formatWeight(report.merchants.goldReceivedPhysical, 2)} جم / ${formatWeight(report.merchants.goldReceived, 2)} E21`,
    `التجار — ذهب مسلم: ${formatWeight(report.merchants.goldDeliveredPhysical, 2)} جم / ${formatWeight(report.merchants.goldDelivered, 2)} E21`,
    `التجار — تحويلات (بدون أثر صافي على المخزون): ${formatWeight(report.merchants.goldTransfers, 2)} E21`,
    `التجار — صافي حركة محل الذهب: ${formatWeight(report.merchants.goldNet, 2)} E21`,
    `التجار — مصنعية / رصيد نقدي: ${formatEgpNumber(report.merchants.workmanshipCash)} ج`,
    `فضة العملاء: بيع ${formatWeight(report.silver.salesWeight, 2)} جم / ${formatEgpNumber(report.silver.salesEgp)} ج — شراء ${formatWeight(report.silver.purchasesWeight, 2)} جم / ${formatEgpNumber(report.silver.purchasesEgp)} ج — صافي داخلي ${formatWeight(report.silver.netMovement, 2)} جم`,
    `فضة التجار: مستلم ${formatWeight(report.silver.merchantReceived, 2)} جم / مسلم ${formatWeight(report.silver.merchantDelivered, 2)} جم`,
    `تحويلات داخلية: ${report.internal.transfers} — كسر داخل ${formatWeight(report.internal.scrapIn, 2)} E21 — خارج ${formatWeight(report.internal.scrapOut, 2)} E21`,
    `اتجاهات داخلية: ${Object.entries(report.internal.directions).map(([key, value]) => `${key}: ${formatWeight(value.e21, 2)} E21`).join('، ') || 'لا يوجد'}`,
    `التجار حسب العيار: ${Object.entries(report.merchants.goldByKarat).filter(([, value]) => value.movements > 0).map(([key, value]) => `${key}: ${formatWeight(value.physical, 2)} جم/${formatWeight(value.e21, 2)} E21`).join('، ') || 'لا يوجد'}`,
    `الحركة الداخلية حسب العيار: ${Object.entries(report.internal.goldByKarat).filter(([, value]) => value.movements > 0).map(([key, value]) => `${key}: ${formatWeight(value.physical, 2)} جم/${formatWeight(value.e21, 2)} E21`).join('، ') || 'لا يوجد'}`,
    `حركات عيارها غير مؤكدة: ${report.merchants.karatConflicts + report.internal.karatConflicts}`,
  ]; return <section className="space-y-4" dir="rtl"><h2 className="text-base font-black text-[#c9a84c]">Smart Daily Management Dashboard</h2><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-[#c9a84c66] bg-[#0e1018] p-5"><h3 className="font-black text-[#f0cc6b]">قرار شراء الذهب الآن</h3><Metric label="متوسط البيع المدمج" value={money(report.decision.blendedSell)} /><Metric label="سقف الشراء المقترح" value={money(report.decision.suggestedPurchase)} strong /><p className="mt-3 text-[11px] text-[#8a8172]">الحاجز الملزم: {report.decision.binding || 'غير متاح'} — ليس ربحًا محاسبيًا.</p><p className="mt-2 text-[10px] text-[#8a8172]">سعر السوق 21: {report.marketPrice === null ? 'سعر السوق لهذا التاريخ غير متاح' : `${formatEgpNumber(report.marketPrice)} ج/جم — مرجع فقط`}</p></div><div className="rounded-3xl border border-[#c9a84c33] bg-[#0e1018] p-5"><h3 className="font-black text-[#f0cc6b]">تحليل الذهب التجاري — هامش التداول</h3><h4 className="mt-3 text-xs text-[#6a9e6a]">مبيعات العملاء</h4>{row('اليوم', report.gold.sales.today)}{row('آخر 7 أيام', report.gold.sales.last7Days)}{row('آخر 30 يومًا', report.gold.sales.last30Days)}<h4 className="mt-3 text-xs text-[#9e6a6a]">مشتريات العملاء</h4>{row('اليوم', report.gold.purchases.today)}{row('آخر 7 أيام', report.gold.purchases.last7Days)}{row('آخر 30 يومًا', report.gold.purchases.last30Days)}<p className="mt-3 text-xs">هامش التداول التاريخي: {money(report.decision.historicalSpread)}</p></div></div><div className="grid gap-4 lg:grid-cols-3"><SmartCard title="ملخص ذهب اليوم" lines={[`الداخل: ${formatWeight(report.gold.physicalIn, 2)} جم / ${formatWeight(report.gold.movementIn, 2)} E21`,`الخارج: ${formatWeight(report.gold.physicalOut, 2)} جم / ${formatWeight(report.gold.movementOut, 2)} E21`,`الصافي: ${formatWeight(report.gold.movementIn - report.gold.movementOut, 2)} E21`]} /><SmartCard title="شرح النقدية" lines={report.cash.categories.map(c => `${c.label}: +${formatEgpNumber(c.cashIn)} / -${formatEgpNumber(c.cashOut)}`)} /><SmartCard title="التجار والفضة والتحويلات" lines={secondary} /><SmartCard title="بيانات مستبعدة" lines={[`حركات غير مؤهلة للتحليل التجاري: ${report.gold.excluded}`, 'لا تؤثر على إقفال الخزنة.']} /></div></section>; };
const SmartCard = ({ title, lines, details }: { title: string; lines: string[]; details?: string[] }) => { const visibleLines = [...new Set(lines)].filter(line => !line.endsWith('لا يوجد') && !/[:\u0020]0(?:\.00)?(?:\u0020|$)/.test(line)); const displayLines = visibleLines.length ? visibleLines : title.includes('التجار') ? ['لا توجد حركة تجار اليوم'] : []; return displayLines.length ? <div className="rounded-3xl border border-[#1a1e2a] bg-[#0e1018] p-4"><h3 className="text-xs font-black text-[#c9a84c]">{title}</h3><div className="mt-3 space-y-2 text-[11px] text-[#ddd8cc]">{displayLines.map(line => <div key={line}><bdi dir="ltr">{line}</bdi></div>)}</div>{details?.length ? <details className="mt-3 text-[10px] text-[#8a8172]"><summary className="cursor-pointer">تفاصيل الاتجاه والعيار</summary><div className="mt-2 space-y-1">{details.map(line => <div key={line}><bdi dir="ltr">{line}</bdi></div>)}</div></details> : null}</div> : null; };

const DimensionSummary = ({ id, title, unit, icon: Icon, accent, report }: { id: DailyJournalDimension; title: string; unit: string; icon: React.ElementType; accent: string; report: ReturnType<typeof buildDailyJournalReport>['dimensions'][DailyJournalDimension]; key?: React.Key }) => {
  const closing = report.closingDebit - report.closingCredit;
  return <div className="space-y-3 rounded-2xl border border-[#1a1e2a] bg-[#080a0f] p-4">
    <div className={cn('flex items-center gap-2 text-xs font-black', accent)}><Icon className="h-4 w-4" />{title}</div>
    <div className="grid grid-cols-2 gap-2 text-xs"><Metric label={'\u0631\u0635\u064a\u062f \u0623\u0648\u0644 \u0627\u0644\u064a\u0648\u0645'} value={`${amount(report.openingDebit - report.openingCredit, id)} ${unit}`} /><Metric label={'\u0648\u0627\u0631\u062f \u0627\u0644\u064a\u0648\u0645'} value={`${amount(report.periodDebit, id)} ${unit}`} /><Metric label={'\u0635\u0627\u062f\u0631 \u0627\u0644\u064a\u0648\u0645'} value={`${amount(report.periodCredit, id)} ${unit}`} /><Metric label={'\u0631\u0635\u064a\u062f \u0622\u062e\u0631 \u0627\u0644\u064a\u0648\u0645'} value={`${amount(closing, id)} ${unit}`} strong /></div>
  </div>;
};
const Metric = ({ label, value, strong }: { label: string; value: string; strong?: boolean }) => <div className="rounded-xl bg-[#0e1018] p-2"><div className="text-[10px] text-[#8a8172]">{label}</div><div className={cn('mt-1 font-mono text-sm text-[#ddd8cc]', strong && 'font-black text-[#c9a84c')}><bdi dir="ltr">{value}</bdi></div></div>;
