import React, { useEffect, useMemo, useState } from 'react';
import { Book, ChevronDown, ChevronRight, Download, Search, X } from 'lucide-react';
import { Account, Entry } from '../../../types';
import { useAppStore } from '../../../store';
import { buildLedgerAccountSelection, buildLedgerCsv, buildLedgerReport, filterLedgerRows, formatBalance, formatLedgerAmount, getAccountKey, getAvailableDimensions, getFilteredTotals, GoldDisplayMode, LedgerDimension, LedgerRow } from '../../../lib/ledgerReport';

const today = () => new Date().toISOString().slice(0, 10);
const yearStart = () => `${new Date().getFullYear()}-01-01`;
const labels: Record<LedgerDimension, string> = { cash: 'نقدية', gold: 'ذهب', silver: 'فضة' };
const original = (row: LedgerRow, value: number, dimension: LedgerDimension, mode: GoldDisplayMode) => mode === 'original' && dimension === 'gold' && row.originalWeight !== undefined && row.karat ? `${formatLedgerAmount(row.originalWeight, 'gold')} — عيار ${row.karat}` : formatLedgerAmount(value, dimension);

export const GeneralLedgerView = React.memo(({ entries }: { entries: Entry[]; startDate?: string; endDate?: string }) => {
  const { accountsDb } = useAppStore();
  const [accountKey, setAccountKey] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const accounts = useMemo(() => accountsDb.filter(a => a.isActive !== false), [accountsDb]);
  const groups = useMemo(() => buildLedgerAccountSelection(accounts, search), [accounts, search]);
  const account = useMemo(() => accounts.find(a => getAccountKey(a) === accountKey), [accounts, accountKey]);

  if (!account) return <AccountSelection groups={groups} search={search} setSearch={setSearch} expanded={expanded} setExpanded={setExpanded} onSelect={a => setAccountKey(getAccountKey(a))} />;
  return <LedgerDetails account={account} accounts={accounts} entries={entries} onBack={() => setAccountKey(null)} />;
});

const AccountSelection = ({ groups, search, setSearch, expanded, setExpanded, onSelect }: { groups: ReturnType<typeof buildLedgerAccountSelection>; search: string; setSearch: (value: string) => void; expanded: Set<string>; setExpanded: React.Dispatch<React.SetStateAction<Set<string>>>; onSelect: (account: Account) => void }) => <section className="space-y-3" dir="rtl">
  <div className="flex items-center gap-2 text-[#f5f1e8]"><Book className="h-5 w-5 text-[#c9a84c]" /><h3 className="font-black">دفتر الأستاذ</h3></div>
  <label className="relative block"><Search className="absolute right-3 top-3 h-4 w-4 text-[#8a8172]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث باسم الحساب" className="w-full rounded-xl border border-[#1a1e2a] bg-[#080a0f] py-2.5 pr-9 pl-3 text-sm text-[#f5f1e8]" /></label>
  <div className="overflow-hidden rounded-2xl border border-[#1a1e2a] bg-[#0e1018]">
    {groups.map(group => { const open = !!search || expanded.has(group.id); return <div key={group.id} className="border-b border-[#1a1e2a] last:border-b-0"><button type="button" onClick={() => setExpanded(previous => { const next = new Set(previous); next.has(group.id) ? next.delete(group.id) : next.add(group.id); return next; })} className="flex w-full items-center gap-2 px-3 py-3 text-right text-xs font-black text-[#c9a84c]">{open ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}<span>{group.label}</span></button>{open && group.accounts.map(item => <button key={item.ledgerEntityId} type="button" onClick={() => onSelect(item.account)} className="flex w-full items-center border-t border-[#1a1e2a]/70 px-5 py-3 text-right text-sm text-[#ddd8cc] active:bg-[#c9a84c]/10"><span className="flex-1">{item.displayName}</span><ChevronRight className="h-4 w-4 text-[#8a8172]" /></button>)}</div>; })}
    {groups.length === 0 && <p className="p-5 text-center text-sm text-[#8a8172]">لا توجد حسابات مطابقة</p>}
  </div>
</section>;

const LedgerDetails = ({ account, accounts, entries, onBack }: { account: Account; accounts: Account[]; entries: Entry[]; onBack: () => void }) => {
  const dimensions = useMemo(() => getAvailableDimensions(account, entries, accounts), [account, entries, accounts]);
  const [dimension, setDimension] = useState<LedgerDimension>('cash');
  const [from, setFrom] = useState(yearStart); const [to, setTo] = useState(today);
  const [operation, setOperation] = useState(''); const [opposite, setOpposite] = useState(''); const [mode, setMode] = useState<GoldDisplayMode>('equivalent21'); const [detail, setDetail] = useState<LedgerRow | null>(null);
  useEffect(() => { if (dimensions.length && !dimensions.includes(dimension)) setDimension(dimensions[0]); }, [dimensions, dimension]);
  const report = useMemo(() => dimensions.includes(dimension) ? buildLedgerReport(entries, accounts, account, dimension, from, to) : null, [entries, accounts, account, dimension, dimensions, from, to]);
  const summary = useMemo(() => dimensions.map(item => ({ dimension: item, report: buildLedgerReport(entries, accounts, account, item, '0000-01-01', today()) })), [dimensions, entries, accounts, account]);
  const rows = useMemo(() => report ? filterLedgerRows(report.rows, operation, opposite) : [], [report, operation, opposite]);
  const totals = useMemo(() => getFilteredTotals(rows), [rows]);
  const types = useMemo(() => [...new Set(report?.rows.map(row => row.operationType) || [])], [report]);
  const opposites = useMemo(() => [...new Set(report?.rows.map(row => row.oppositeAccount) || [])], [report]);
  const period = (start: Date, end: Date) => { setFrom(start.toISOString().slice(0, 10)); setTo(end.toISOString().slice(0, 10)); };
  const exportCsv = () => { if (!report) return; const csv = buildLedgerCsv({ accountName: account.name, dimension, startDate: from, endDate: to, report, rows, goldDisplayMode: mode }); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `ledger_${account.name.replace(/[\\/:*?"<>|]/g, '-')}_${labels[dimension]}_${from}_${to}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <section className="space-y-3 pb-4" dir="rtl">
    <button type="button" onClick={onBack} className="flex items-center gap-1 text-sm font-bold text-[#c9a84c]"><ChevronRight className="h-5 w-5" /> رجوع للحسابات</button><h3 className="text-lg font-black text-[#f5f1e8]">{account.name}</h3>
    <section className="grid grid-cols-1 gap-2 rounded-2xl border border-[#1a1e2a] bg-[#0e1018] p-3 sm:grid-cols-3">{summary.map(item => <div key={item.dimension}><p className="text-[10px] text-[#8a8172]">{labels[item.dimension]}</p><p className="text-sm font-bold text-[#f5f1e8]">{formatBalance(item.report.closingBalance, item.dimension)}</p></div>)}</section>
    {dimensions.length === 0 ? <p className="rounded-xl border border-[#1a1e2a] p-4 text-sm text-[#8a8172]">لا توجد حركات محاسبية لهذا الحساب</p> : <>
      <section className="space-y-3 rounded-2xl border border-[#1a1e2a] bg-[#0e1018] p-3"><div className="flex items-center justify-between"><div className="flex gap-1">{dimensions.map(item => <button key={item} onClick={() => setDimension(item)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${dimension === item ? 'bg-[#c9a84c] text-[#080a0f]' : 'bg-[#080a0f] text-[#8a8172]'}`}>{labels[item]}</button>)}</div><button onClick={exportCsv} className="flex items-center gap-1 text-xs text-[#c9a84c]"><Download className="h-4 w-4" />تصدير CSV</button></div><div className="flex flex-wrap gap-1 text-[11px]"><button onClick={() => period(new Date(new Date().getFullYear(), new Date().getMonth(), 1), new Date())}>الشهر الحالي</button><button onClick={() => period(new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1), new Date(new Date().getFullYear(), new Date().getMonth(), 0))}>الشهر السابق</button><button onClick={() => period(new Date(new Date().getFullYear(), 0, 1), new Date())}>السنة الحالية</button><button onClick={() => period(new Date(new Date().getFullYear() - 1, 0, 1), new Date(new Date().getFullYear() - 1, 11, 31))}>السنة السابقة</button></div><div className="grid grid-cols-2 gap-2"><input type="date" value={from} onChange={e => setFrom(e.target.value)} className="rounded-lg bg-[#080a0f] p-2 text-xs text-[#ddd8cc]" /><input type="date" min={from} value={to} onChange={e => setTo(e.target.value)} className="rounded-lg bg-[#080a0f] p-2 text-xs text-[#ddd8cc]" /></div>{dimension === 'gold' && <button onClick={() => setMode(value => value === 'equivalent21' ? 'original' : 'equivalent21')} className="text-xs text-[#c9a84c]">{mode === 'equivalent21' ? 'عرض الوزن الأصلي' : 'عرض وزن 21 المكافئ'}</button>}</section>
      {report && <><section className="grid grid-cols-2 gap-2 rounded-2xl border border-[#1a1e2a] bg-[#0e1018] p-3 text-xs text-[#f5f1e8]"><Stat label="رصيد أول المدة" value={formatBalance(report.openingBalance, dimension)} /><Stat label="إجمالي المدين" value={formatLedgerAmount(totals.totalDebit, dimension)} /><Stat label="إجمالي الدائن" value={formatLedgerAmount(totals.totalCredit, dimension)} /><Stat label="رصيد آخر المدة" value={formatBalance(report.closingBalance, dimension)} /></section><section className="space-y-3 rounded-2xl border border-[#1a1e2a] bg-[#0e1018] p-3"><div className="grid grid-cols-2 gap-2"><select value={operation} onChange={e => setOperation(e.target.value)} className="bg-[#080a0f] p-2 text-xs text-[#ddd8cc]"><option value="">نوع العملية</option>{types.map(value => <option key={value}>{value}</option>)}</select><select value={opposite} onChange={e => setOpposite(e.target.value)} className="bg-[#080a0f] p-2 text-xs text-[#ddd8cc]"><option value="">الحساب المقابل</option>{opposites.map(value => <option key={value}>{value}</option>)}</select></div>{rows.length === 0 ? <p className="py-8 text-center text-sm text-[#8a8172]">لا توجد حركات خلال الفترة</p> : <div className="overflow-x-auto"><table className="min-w-[680px] w-full text-right text-xs"><thead className="text-[#c9a84c]"><tr>{['التاريخ', 'رقم العملية', 'البيان', 'مدين', 'دائن', 'الرصيد'].map(value => <th key={value} className="p-2">{value}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.entry.id || row.operationNumber}-${index}`} onClick={() => setDetail(row)} className="cursor-pointer border-t border-[#1a1e2a] text-[#ddd8cc]"><td className="p-2">{row.date}</td><td className="p-2">{row.operationNumber}</td><td className="p-2">{row.operationType} — {row.oppositeAccount}</td><td className="p-2">{original(row, row.debit, dimension, mode)}</td><td className="p-2">{original(row, row.credit, dimension, mode)}</td><td className="p-2">{formatBalance(row.balance, dimension)}</td></tr>)}</tbody></table></div>}</section></>}
    </>}{detail && <OperationDetails detail={detail} close={() => setDetail(null)} />}
  </section>;
};
const Stat = ({ label, value }: { label: string; value: string }) => <div><p className="text-[10px] text-[#8a8172]">{label}</p><p className="font-bold">{value}</p></div>;
const OperationDetails = ({ detail, close }: { detail: LedgerRow; close: () => void }) => <div className="fixed inset-0 z-50 flex items-end bg-black/60 p-3" onClick={close}><section className="w-full rounded-2xl bg-[#0e1018] p-4 text-xs text-[#ddd8cc]" onClick={event => event.stopPropagation()}><button className="float-left" onClick={close}><X /></button><h4 className="font-black text-[#f5f1e8]">تفاصيل العملية</h4><p>رقم العملية: {detail.operationNumber}</p><p>التاريخ: {detail.date}</p><p>الحساب المقابل: {detail.oppositeAccount}</p><p>قيمة العملية (للعرض فقط): {formatLedgerAmount(Number(detail.entry.cash) || 0, 'cash')}</p><p>الوزن: {detail.entry.weight || '—'} {detail.entry.karat ? `— عيار ${detail.entry.karat}` : ''}</p><p>الكمية: {detail.entry.count || '—'}</p><p>ملاحظات: {detail.entry.notes || '—'}</p></section></div>;