import React, { useMemo, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import { useAppStore } from '../../../store';
import { buildInventoryProfitabilityReport, groupProfitabilityRowsByMonth, type InventoryProfitabilityScope } from '../../../lib/inventoryProfitabilityReport';

const money = (minor: number) => new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 0 }).format(minor / 100);
const grams = (units: number) => new Intl.NumberFormat('ar-EG', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(units / 100);
const price = (minor: number, units: number) => units ? new Intl.NumberFormat('ar-EG', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(minor / units) : '—';
const classificationLabel: Record<string, string> = { opening: 'رصيد افتتاحي', customer_purchase: 'شراء من عميل', merchant_receipt: 'استلام من تاجر', merchant_delivery: 'تسليم لتاجر', sale: 'بيع', tafyeet: 'تصفية داخلية', transfer: 'تحويل داخلي', shortage: 'عجز', surplus: 'زيادة', two_sided_adjustment: 'تسوية', quantity_only: 'حركة كمية', non_cost: 'غير مؤثر' };
const card = 'rounded-2xl border border-[#1a1e2a] bg-[#0e1018] p-3';

export const InventoryProfitabilityReportView: React.FC = () => {
  const { costCalculationRun, accountsDb, requestCostRetry } = useAppStore();
  const goldAccounts = useMemo(() => accountsDb.filter(account => account.id && account.is_inventory && account.metal === 'gold'), [accountsDb]);
  const [scope, setScope] = useState<InventoryProfitabilityScope>({ type: 'gold-total' });
  const today = new Date();
  const [range, setRange] = useState(() => ({ start: `${today.getFullYear()}-01-01`, end: today.toISOString().slice(0, 10) }));
  const report = useMemo(() => costCalculationRun.status === 'valid' && costCalculationRun.timeline?.valid
    ? buildInventoryProfitabilityReport(costCalculationRun.timeline, goldAccounts, scope, range.start, range.end) : null,
  [costCalculationRun.status, costCalculationRun.timeline, goldAccounts, scope, range]);
  const allTimeReport = useMemo(() => costCalculationRun.status === 'valid' && costCalculationRun.timeline?.valid
    ? buildInventoryProfitabilityReport(costCalculationRun.timeline, goldAccounts, scope) : null,
  [costCalculationRun.status, costCalculationRun.timeline, goldAccounts, scope]);
  const monthly = useMemo(() => allTimeReport ? groupProfitabilityRowsByMonth(allTimeReport)
    .filter(row => row.month >= range.start.slice(0, 7) && row.month <= range.end.slice(0, 7)) : [], [allTimeReport, range]);

  if (costCalculationRun.status !== 'valid' || !costCalculationRun.timeline?.valid) return <div className="rounded-3xl border border-red-500/30 bg-red-500/10 p-6 text-red-100"><div className="flex items-center gap-2 font-black"><AlertTriangle className="h-5 w-5" />تحليل وربحية المخزون غير متاح</div><p className="mt-2 text-xs leading-6">{costCalculationRun.status === 'running' ? 'جارٍ إعادة احتساب التكلفة، يرجى الانتظار.' : costCalculationRun.error ? `${costCalculationRun.error.code}: ${costCalculationRun.error.message}` : 'لا توجد Cost Timeline صالحة بعد.'}</p><button type="button" onClick={requestCostRetry} className="mt-4 rounded-xl bg-[#c9a84c] px-4 py-2 text-xs font-black text-[#080a0f]">إعادة المحاولة</button></div>;
  if (!report) return null;
  const setQuickRange = (kind: 'current' | 'previous' | 'year' | 'lastYear') => {
    const now = new Date(); const y = now.getFullYear(); const m = now.getMonth();
    if (kind === 'current') setRange({ start: new Date(y, m, 1).toISOString().slice(0, 10), end: new Date(y, m + 1, 0).toISOString().slice(0, 10) });
    if (kind === 'previous') setRange({ start: new Date(y, m - 1, 1).toISOString().slice(0, 10), end: new Date(y, m, 0).toISOString().slice(0, 10) });
    if (kind === 'year') setRange({ start: `${y}-01-01`, end: `${y}-12-31` });
    if (kind === 'lastYear') setRange({ start: `${y - 1}-01-01`, end: `${y - 1}-12-31` });
  };
  const rowsFor = (classification: string) => report.rows.filter(row => row.result.classification === classification);
  const stat = (classification: string, direction: 'in' | 'out') => {
    const rows = rowsFor(classification); const units = rows.reduce((sum, row) => sum + (direction === 'in' ? row.incomingE21Units : row.outgoingE21Units), 0);
    const cost = rows.reduce((sum, row) => sum + (direction === 'in' ? row.incomingCostMinor : row.outgoingCostMinor), 0);
    return { rows, units, cost };
  };
  const purchases = stat('customer_purchase', 'in'); const receipts = stat('merchant_receipt', 'in'); const sales = stat('sale', 'out'); const deliveries = stat('merchant_delivery', 'out');
  const purchasePrices = movementPrices(purchases.rows, 'incoming');
  const salePrices = movementPrices(sales.rows, 'sale');
  const profitableSales = sales.rows.filter(row => (row.result.profitMinor ?? 0) >= 0);
  const lossSales = sales.rows.filter(row => (row.result.profitMinor ?? 0) < 0);
  const netResult = report.grossProfitMinor + report.adjustmentGainMinor - report.adjustmentLossMinor;
  const scopeLabel = scope.type === 'gold-total' ? 'إجمالي الذهب' : scope.type === 'karat' ? `عيار ${scope.karat}` : goldAccounts.find(account => account.id === scope.accountId)?.name ?? 'صنف';
  const rankRows = scope.type === 'item' ? [] : goldAccounts.filter(account => report.accountIds.includes(account.id!)).map(account => ({ account, summary: buildInventoryProfitabilityReport(costCalculationRun.timeline!, goldAccounts, { type: 'item', accountId: account.id! }, range.start, range.end) }));

  return <div className="space-y-4 pb-20" dir="rtl">
    <div className={card}><div className="flex items-center justify-between gap-2"><div><h3 className="font-black text-[#f5f1e8]">تحليل وربحية المخزون</h3><p className="mt-1 text-[10px] text-[#8a8172]">مصدر التقرير: حركة تكلفة المخزون المعتمدة</p></div><button type="button" onClick={requestCostRetry} title="إعادة المحاولة" className="rounded-xl border border-[#1a1e2a] p-2 text-[#c9a84c]"><RefreshCw className="h-4 w-4" /></button></div>
      <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5"><button onClick={() => setScope({ type: 'gold-total' })} className={`rounded-xl p-2 text-xs font-black ${scope.type === 'gold-total' ? 'bg-[#c9a84c] text-[#080a0f]' : 'bg-[#080a0f] text-[#ddd8cc]'}`}>إجمالي الذهب</button>{([18, 21, 24] as const).map(karat => <button key={karat} onClick={() => setScope({ type: 'karat', karat })} className={`rounded-xl p-2 text-xs font-black ${scope.type === 'karat' && scope.karat === karat ? 'bg-[#c9a84c] text-[#080a0f]' : 'bg-[#080a0f] text-[#ddd8cc]'}`}>عيار {karat}</button>)}<select value={scope.type === 'item' ? scope.accountId : ''} onChange={event => event.target.value && setScope({ type: 'item', accountId: event.target.value })} className="rounded-xl bg-[#080a0f] p-2 text-xs text-[#ddd8cc]"><option value="">صنف محدد…</option>{goldAccounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></div>
    </div>
    <div className={card}><div className="mb-2 text-xs font-black text-[#f5f1e8]">الفترة</div><div className="grid grid-cols-2 gap-2"><input type="date" value={range.start} onChange={event => setRange({ ...range, start: event.target.value })} className="rounded-xl bg-[#080a0f] p-2 text-xs text-[#ddd8cc]"/><input type="date" value={range.end} onChange={event => setRange({ ...range, end: event.target.value })} className="rounded-xl bg-[#080a0f] p-2 text-xs text-[#ddd8cc]"/></div><div className="mt-2 flex flex-wrap gap-1">{[['current', 'الشهر الحالي'], ['previous', 'الشهر السابق'], ['year', 'السنة الحالية'], ['lastYear', 'السنة السابقة']].map(([id, label]) => <button key={id} onClick={() => setQuickRange(id as any)} className="rounded-lg border border-[#1a1e2a] px-2 py-1 text-[10px] text-[#c9a84c]">{label}</button>)}</div></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-5"><Metric label={`${scopeLabel} الحالي E21`} value={`${grams(report.currentE21Units)} جم`} /><Metric label="الوزن الفعلي الحالي" value={`${grams(report.currentPhysicalUnits)} جم`} /><Metric label="القيمة الدفترية" value={`${money(report.currentBookValueMinor)} ج.م`} /><Metric label="متوسط التكلفة WAC" value={`${price(report.currentBookValueMinor, report.currentE21Units)} ج.م/جم`} /><Metric label="صافي حركة الفترة" value={`${grams(report.externalIncomingE21Units - report.externalOutgoingE21Units)} جم`} /></div>
    <section className={card}><h4 className="font-black text-[#f5f1e8]">الحركة خلال الفترة</h4><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Metric label="إجمالي الداخل الخارجي" value={`${grams(report.externalIncomingE21Units)} جم E21`} /><Metric label="إجمالي الخارج الخارجي" value={`${grams(report.externalOutgoingE21Units)} جم E21`} /></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Movement label="شراء من عميل" detail={`متوسط ${price(purchases.cost, purchases.units)} · أدنى ${purchasePrices.low} · أعلى ${purchasePrices.high} · آخر ${purchasePrices.latest} ج.م/جم`} units={purchases.units} amount={purchases.cost} count={purchases.rows.length}/><Movement label="استلام من تاجر" detail={`متوسط التكلفة المعترف بها ${price(receipts.cost, receipts.units)} ج.م/جم`} units={receipts.units} amount={receipts.cost} count={receipts.rows.length}/><Movement label="بيع" detail={`متوسط ${price(report.saleAmountMinor, sales.units)} · أدنى ${salePrices.low} · أعلى ${salePrices.high} · آخر ${salePrices.latest} · متوسط COGS ${price(report.totalCogsMinor, sales.units)}`} units={sales.units} amount={report.saleAmountMinor} count={sales.rows.length}/><Movement label="تسليم لتاجر" detail="قيمة دفترية محررة" units={deliveries.units} amount={deliveries.cost} count={deliveries.rows.length}/></div></section>
    <section className={card}><h4 className="font-black text-[#f5f1e8]">الربحية المحققة</h4><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="إجمالي ربح المبيعات" value={`${money(report.grossProfitMinor)} ج.م`} /><Metric label="مكاسب الزيادة" value={`${money(report.adjustmentGainMinor)} ج.م`} /><Metric label="خسائر العجز" value={`${money(report.adjustmentLossMinor)} ج.م`} /><Metric label="صافي النتيجة" value={`${money(netResult)} ج.م`} /></div><p className="mt-2 text-[10px] text-[#ddd8cc]">مبيعات رابحة: {profitableSales.length} · خاسرة: {lossSales.length} · ربح/جم: {price(report.grossProfitMinor, sales.units)} ج.م · هامش: {report.saleAmountMinor ? `${((report.grossProfitMinor / report.saleAmountMinor) * 100).toFixed(2)}%` : '—'}</p><p className="mt-1 text-[10px] text-[#8a8172]">ربح البيع من saleAmount وCOGS وprofit المعتمد. لا يدخل الفرق السوقي غير المحقق في الربح المحقق.</p></section>
    {rankRows.length > 0 && <Table title="ترتيب الأصناف داخل المجموعة" headers={['الصنف', 'رصيد E21', 'شراء عميل', 'بيع', 'COGS', 'ربح إجمالي', 'ربح/جم', 'هامش']}><>{rankRows.map(({ account, summary }) => <tr key={account.id} className="border-t border-[#1a1e2a]"><td className="p-2">{account.name}</td><td>{grams(summary.currentE21Units)}</td><td>{grams(statFor(summary, 'customer_purchase', 'in').units)}</td><td>{grams(statFor(summary, 'sale', 'out').units)}</td><td>{money(summary.totalCogsMinor)}</td><td>{money(summary.grossProfitMinor)}</td><td>{price(summary.grossProfitMinor, statFor(summary, 'sale', 'out').units)}</td><td>{summary.saleAmountMinor ? `${((summary.grossProfitMinor / summary.saleAmountMinor) * 100).toFixed(2)}%` : '—'}</td></tr>)}</></Table>}
    <Table title="التحليل الشهري" headers={['الشهر', 'افتتاح E21', 'شراء عميل', 'متوسط الشراء', 'استلام تاجر', 'إجمالي داخل', 'بيع', 'متوسط البيع', 'تسليم تاجر', 'إجمالي خارج', 'COGS', 'ربح البيع', 'زيادة/عجز', 'صافي النتيجة', 'إقفال E21']}><>{monthly.map(row => <tr key={row.month} className="border-t border-[#1a1e2a]"><td className="p-2">{row.month}</td><td>{grams(row.openingE21Units)}</td><td>{grams(row.customerPurchaseE21Units)}</td><td>{price(row.customerPurchaseCostMinor, row.customerPurchaseE21Units)}</td><td>{grams(row.merchantReceiptE21Units)}</td><td>{grams(row.incomingE21Units)}</td><td>{grams(row.saleE21Units)}</td><td>{price(row.saleAmountMinor, row.saleE21Units)}</td><td>{grams(row.merchantDeliveryE21Units)}</td><td>{grams(row.outgoingE21Units)}</td><td>{money(row.cogsMinor)}</td><td>{money(row.grossProfitMinor)}</td><td>{money(row.adjustmentGainMinor - row.adjustmentLossMinor)}</td><td>{money(row.grossProfitMinor + row.adjustmentGainMinor - row.adjustmentLossMinor)}</td><td>{grams(row.closingE21Units)}</td></tr>)}</></Table>
    <Table title="تفاصيل العمليات" headers={['التاريخ', 'رقم العملية', 'المعرف', 'الحساب', 'العيار', 'الوزن الفعلي', 'التصنيف', 'E21 داخل', 'E21 خارج', 'تكلفة داخل', 'تكلفة خارج', 'بيع', 'COGS', 'ربح/خسارة', 'زيادة', 'عجز']}><>{report.rows.map((row, index) => <tr key={`${row.result.operationId}-${index}`} className="border-t border-[#1a1e2a]"><td className="p-2">{row.result.entry.date}</td><td>{row.result.entry.operationNo ?? row.result.entry.invoiceNumber ?? '—'}</td><td>{row.result.operationId}</td><td>{goldAccounts.find(account => account.id === row.accountId)?.name ?? row.accountId}</td><td>{goldAccounts.find(account => account.id === row.accountId)?.karat ?? '—'}</td><td>{grams(row.incomingPhysicalUnits || row.outgoingPhysicalUnits)}</td><td>{classificationLabel[row.result.classification]}</td><td>{grams(row.incomingE21Units)}</td><td>{grams(row.outgoingE21Units)}</td><td>{money(row.incomingCostMinor)}</td><td>{money(row.outgoingCostMinor)}</td><td>{money(row.result.saleAmountMinor)}</td><td>{money(row.result.totalCogsMinor)}</td><td>{money(row.result.profitMinor ?? 0)}</td><td>{money(row.result.adjustmentGainMinor)}</td><td>{money(row.result.adjustmentLossMinor)}</td></tr>)}</></Table>
  </div>;
};

const statFor = (report: ReturnType<typeof buildInventoryProfitabilityReport>, classification: string, direction: 'in' | 'out') => ({ units: report.rows.filter(row => row.result.classification === classification).reduce((sum, row) => sum + (direction === 'in' ? row.incomingE21Units : row.outgoingE21Units), 0) });
const movementPrices = (rows: ReturnType<typeof buildInventoryProfitabilityReport>['rows'], kind: 'incoming' | 'sale') => {
  const values = rows.filter(row => (kind === 'incoming' ? row.incomingE21Units : row.outgoingE21Units) > 0).map(row => ({ date: row.result.entry.date, value: (kind === 'incoming' ? row.incomingCostMinor : row.result.saleAmountMinor) / (kind === 'incoming' ? row.incomingE21Units : row.outgoingE21Units) }));
  return { low: values.length ? values.reduce((a, b) => a.value < b.value ? a : b).value.toFixed(2) : '—', high: values.length ? values.reduce((a, b) => a.value > b.value ? a : b).value.toFixed(2) : '—', latest: values.sort((a, b) => a.date.localeCompare(b.date)).at(-1)?.value.toFixed(2) ?? '—' };
};
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl bg-[#080a0f] p-3 text-center"><div className="text-[10px] text-[#8a8172]">{label}</div><div className="mt-1 font-mono text-xs font-black text-[#ddd8cc]">{value}</div></div>;
const Movement = ({ label, detail, units, amount, count }: { label: string; detail: string; units: number; amount: number; count: number }) => <div className="rounded-xl bg-[#080a0f] p-3 text-xs"><div className="font-black text-[#f5f1e8]">{label}</div><div className="mt-1 text-[#ddd8cc]">{grams(units)} جم E21 · {money(amount)} ج.م</div><div className="mt-1 text-[10px] text-[#8a8172]">{count} عملية · {detail}</div></div>;
const Table = ({ title, headers, children }: { title: string; headers: string[]; children: React.ReactNode }) => <section className={`${card} overflow-x-auto`}><h4 className="mb-3 font-black text-[#f5f1e8]">{title}</h4><table className="min-w-max w-full text-right text-[10px] text-[#ddd8cc]"><thead className="text-[#8a8172]"><tr>{headers.map(header => <th key={header} className="p-2 font-bold">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></section>;
