import fs from 'node:fs';
import path from 'node:path';

type Row = Record<string,string>;
type Entry = { id:string; tx:string; debit:string; credit:string; date:string; cash:string|number; weight:string|number; arabicWeight:string|number; count:string|number; invoiceNumber?:string; legacyOperationId?:string };
type Status = 'canonical_balanced'|'legacy_only'|'operational_only'|'inventory_only'|'non_journal'|'unresolved'|'invalid';
type Variant = {
 operationType:string; arabicLabel:string; variant:string; documentCount:number; triggerConditions:string; requiredFields:string;
 cashPosting:string; goldPosting:string; silverPosting:string; inventoryEffect:string; merchantLiabilityEffect:string;
 workmanshipEffect:string; costEffect:string; profitEffect:string; revenueEffect:string; expenseEffect:string; equityEffect:string;
 fallbackPolicy:string; status:Status; decisionId:string; sourceRule:string; confidence:'high'|'medium'|'low'; blockingDecision:string;
 cashDebitAccount:string; cashCreditAccount:string; goldDebitAccount:string; goldCreditAccount:string; silverDebitAccount:string; silverCreditAccount:string;
 sourceOperationIds:string; costStatus:'confirmed'|'unresolved'|'not_applicable'; notes:string;
};
const root=process.cwd();
const parseCsv=(text:string):Row[]=>{const records:string[][]=[];let rec:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===','){rec.push(field);field='';}else if(c==='\n'){rec.push(field);records.push(rec);rec=[];field='';}else if(c!=='\r')field+=c;}if(field||rec.length)records.push([...rec,field]);const h=(records.shift()||[]).map(x=>x.replace(/^\uFEFF/,''));return records.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||''])))};
const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;
const writeCsv=(name:string,rows:Record<string,unknown>[],cols:string[])=>fs.writeFileSync(path.join(root,name),'\uFEFF'+[cols.map(esc).join(','),...rows.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\r\n')+'\r\n','utf8');
const n=(v:unknown)=>Number(v||0);
const norm=(s:string)=>s.normalize('NFKC').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[\u064B-\u065F]/g,'').replace(/[\s_-]+/g,' ').trim();
const preview=parseCsv(fs.readFileSync(path.join(root,'approved_normalized_preview.csv'),'utf8'));
const entries=preview.map(r=>({...JSON.parse(r.proposed_import_document),id:r.document_id} as Entry));
if(entries.length!==2169)throw new Error(`Legacy count ${entries.length}`);
const audit=JSON.parse(fs.readFileSync(path.join(root,'accounting_reconciliation_audit.json'),'utf8'));
const aliases=parseCsv(fs.readFileSync(path.join(root,'csv_reference_account_aliases.csv'),'utf8'));
const accountMap=new Map<string,{id:string;name:string}>();
for(const r of aliases){const ids=JSON.parse(r.seed_account_ids||'[]') as string[];const names=JSON.parse(r.seed_account_names||'[]') as string[];if(ids.length===1)accountMap.set(norm(r.normalized_account_name),{id:ids[0],name:names[0]||r.normalized_account_name});}
const account=(name:string)=>{const hit=accountMap.get(norm(name));return hit?`${hit.id} | ${hit.name}`:`historical-name:${name} | ${name}`};
const A={cash:'seed-account-43aee8a824522365db1a | الخزنة',drawings:'seed-account-cbb3feca38a9c9b79877 | المسحوبات',
 retainedCash:'canonical:equity:retained-results:cash | Retained Cash Results',retainedGold:'canonical:equity:retained-results:gold | Retained Gold Results',retainedSilver:'canonical:equity:retained-results:silver | Retained Silver Results',
 goldCost:'canonical:asset:inventory-carrying-cost:gold | Gold Inventory Carrying Cost',silverCost:'canonical:asset:inventory-carrying-cost:silver | Silver Inventory Carrying Cost',accessoryCost:'canonical:asset:inventory-carrying-cost:accessories | Accessories Inventory Carrying Cost',
 goldCogs:'canonical:expense:cogs:gold | Gold COGS',silverCogs:'canonical:expense:cogs:silver | Silver COGS',accessoryCogs:'canonical:expense:cogs:accessories | Accessories COGS',
 goldRevenue:'canonical:revenue:sales:gold | Gold Sales Revenue',silverRevenue:'canonical:revenue:sales:silver | Silver Sales Revenue',accessoryRevenue:'canonical:revenue:sales:accessories | Accessories Sales Revenue',
 goldBought:'canonical:metal-flow:gold:acquired | Gold Weight Acquired',goldSold:'canonical:metal-flow:gold:sold | Gold Weight Sold',silverBought:'canonical:metal-flow:silver:acquired | Silver Weight Acquired',silverSold:'canonical:metal-flow:silver:sold | Silver Weight Sold'};
const operationName:Record<string,string>={'بيع ذهب':'customer_gold_sale','شراء ذهب':'customer_gold_purchase','بيع �?ضة':'customer_silver_sale','شراء �?ضة':'customer_silver_purchase','بيع ملحقات':'accessory_sale','شراء ملحقات':'accessory_purchase','تي�?يت':'inventory_transformation','تحويل':'inventory_transfer','تسوية':'inventory_adjustment','مسحوبات':'personal_drawings','ايرادات اخري':'other_income','م ا ع':'operating_expense','م ت':'merchant_to_merchant_transfer','تاجر ذهب':'merchant_weight_received','تاجر �?ضة':'merchant_weight_received','حساب تاجر ذهب':'merchant_settlement','حساب تاجر �?ضة':'merchant_settlement','حوالة':'cash_transfer','د�?ع لعميل':'customer_payment','قبض من عميل':'customer_receipt','شراء اصل':'fixed_asset_purchase'};
const variants:Variant[]=[];const assigned=new Set<string>();
const add=(v:Variant,group:Entry[])=>{for(const e of group){if(assigned.has(e.id))throw new Error(`Overlap ${e.id}`);assigned.add(e.id);}variants.push({...v,documentCount:group.length,sourceOperationIds:group.map(e=>e.id).join('|')});};
const base=(operationType:string,label:string,variant:string):Variant=>({operationType,arabicLabel:label,variant,documentCount:0,triggerConditions:'',requiredFields:'',cashPosting:'none',goldPosting:'none',silverPosting:'none',inventoryEffect:'none',merchantLiabilityEffect:'none',workmanshipEffect:'none',costEffect:'none',profitEffect:'none',revenueEffect:'none',expenseEffect:'none',equityEffect:'none',fallbackPolicy:'reject; no balancing plug; no market-price cost fallback',status:'canonical_balanced',decisionId:'P21-APPROVED',sourceRule:'Owner-approved Phase 2.1 decisions + Phase 2 source inventory',confidence:'high',blockingDecision:'',cashDebitAccount:'',cashCreditAccount:'',goldDebitAccount:'',goldCreditAccount:'',silverDebitAccount:'',silverCreditAccount:'',sourceOperationIds:'',costStatus:'not_applicable',notes:''});
const grouped=new Map<string,Entry[]>();
for(const e of entries.filter(x=>x.tx!=='قيد ا�?تتاحي')){const key=[e.tx,e.debit,e.credit].join('\u241f');grouped.set(key,[...(grouped.get(key)||[]),e]);}
for(const [,group] of grouped){const e=group[0];const op=operationName[e.tx]||`legacy_${norm(e.tx).replace(/ /g,'_')}`;const v=base(op,e.tx,`${op}:${norm(e.debit)}->${norm(e.credit)}`);v.triggerConditions=`tx == ${JSON.stringify(e.tx)} AND debit == ${JSON.stringify(e.debit)} AND credit == ${JSON.stringify(e.credit)}`;v.requiredFields='sourceOperationId,date,debit,credit; positive amount for each used dimension';v.cashDebitAccount=account(e.debit);v.cashCreditAccount=account(e.credit);v.cashPosting=group.some(x=>n(x.cash)!==0)?`Dr ${v.cashDebitAccount}; Cr ${v.cashCreditAccount}; amount=cash`:'none';v.goldDebitAccount=account(e.debit);v.goldCreditAccount=account(e.credit);v.goldPosting=group.some(x=>n(x.arabicWeight)!==0)?`Dr ${v.goldDebitAccount}; Cr ${v.goldCreditAccount}; amount=Equivalent-21`:'none';v.silverDebitAccount=account(e.debit);v.silverCreditAccount=account(e.credit);v.silverPosting=group.some(x=>n(x.weight)!==0&&(e.tx.includes('�?ضة')||e.debit.includes('�?ضة')||e.credit.includes('�?ضة')))?`Dr ${v.silverDebitAccount}; Cr ${v.silverCreditAccount}; amount=physical silver g`:'none';
 if(e.tx==='بيع ذهب'||e.tx==='شراء ذهب'){const sale=e.tx==='بيع ذهب';v.operationType=sale?'customer_gold_sale':'customer_gold_purchase';v.requiredFields+='; cash,physicalWeight,goldEquivalent21Snapshot,productId'+(sale?'; confirmedPreSaleWac':'');v.cashDebitAccount=sale?A.cash:A.goldCost;v.cashCreditAccount=sale?A.goldRevenue:A.cash;v.cashPosting=sale?`Dr ${A.cash}; Cr ${A.goldRevenue}; Dr ${A.goldCogs}; Cr ${A.goldCost}`:`Dr ${A.goldCost}; Cr ${A.cash}`;v.goldDebitAccount=sale?A.goldSold:account(e.debit);v.goldCreditAccount=sale?account(e.credit):A.goldBought;v.goldPosting=`Dr ${v.goldDebitAccount}; Cr ${v.goldCreditAccount}; amount=Equivalent-21`;v.inventoryEffect=sale?'physical gold decreases exactly once':'physical gold increases exactly once';v.costEffect=sale?'Dr Gold COGS / Cr Gold Inventory Carrying Cost at pre-sale WAC':'add acquisition cash cost to Gold Inventory Carrying Cost and WAC';v.profitEffect=sale?'revenue minus original carrying cost; no duplicate inventory effect':'none';v.revenueEffect=sale?'+Gold Sales Revenue':'none';v.expenseEffect=sale?'+Gold COGS':'none';v.costStatus='confirmed';v.decisionId='P21-01,P21-07';}
 if(e.tx==='بيع �?ضة'||e.tx==='شراء �?ضة'){const sale=e.tx==='بيع �?ضة';v.operationType=sale?'customer_silver_sale':'customer_silver_purchase';v.requiredFields+='; cash,physicalSilverWeight,productId'+(sale?'; confirmedPreSaleWac':'');v.cashDebitAccount=sale?A.cash:A.silverCost;v.cashCreditAccount=sale?A.silverRevenue:A.cash;v.cashPosting=sale?`Dr ${A.cash}; Cr ${A.silverRevenue}; Dr ${A.silverCogs}; Cr ${A.silverCost}`:`Dr ${A.silverCost}; Cr ${A.cash}`;v.silverDebitAccount=sale?A.silverSold:account(e.debit);v.silverCreditAccount=sale?account(e.credit):A.silverBought;v.silverPosting=`Dr ${v.silverDebitAccount}; Cr ${v.silverCreditAccount}; amount=physical silver g`;v.inventoryEffect=sale?'physical silver decreases exactly once':'physical silver increases exactly once';v.costEffect=sale?'Dr Silver COGS / Cr Silver Inventory Carrying Cost at original pre-sale WAC':'add acquisition cash cost to Silver Inventory Carrying Cost and WAC';v.profitEffect=sale?'revenue minus carrying cost':'none';v.revenueEffect=sale?'+Silver Sales Revenue':'none';v.expenseEffect=sale?'+Silver COGS':'none';v.costStatus='confirmed';v.decisionId='P21-01,P21-07';}
 if(e.tx==='بيع ملحقات'||e.tx==='شراء ملحقات'){const sale=e.tx==='بيع ملحقات';v.operationType=sale?'accessory_sale':'accessory_purchase';v.requiredFields+='; cash,quantity,productId'+(sale?'; confirmedPreSaleWac':'');v.cashDebitAccount=sale?A.cash:A.accessoryCost;v.cashCreditAccount=sale?A.accessoryRevenue:A.cash;v.cashPosting=sale?`Dr ${A.cash}; Cr ${A.accessoryRevenue}; Dr ${A.accessoryCogs}; Cr ${A.accessoryCost}`:`Dr ${A.accessoryCost}; Cr ${A.cash}`;v.goldPosting='none';v.silverPosting='none';v.inventoryEffect=sale?'accessory quantity decreases exactly once':'accessory quantity increases exactly once';v.costEffect=sale?'Dr Accessories COGS / Cr Accessories Inventory Carrying Cost at pre-sale WAC':'add acquisition cost to Accessories WAC';v.profitEffect=sale?'revenue minus carrying cost':'none';v.costStatus='confirmed';v.decisionId='P21-01,P21-07';}
 if(e.tx==='مسحوبات'){const reversed=norm(e.debit)===norm('الخزنة');v.operationType='personal_drawings';v.requiredFields+='; cash';v.goldPosting='none';v.silverPosting='none';if(reversed){v.status='legacy_only';v.variant='personal_drawings:legacy_direction_exception';v.triggerConditions+=` AND sourceOperationId IN (${group.map(x=>JSON.stringify(x.id)).join(',')})`;v.fallbackPolicy='preserve historical row unchanged; never promote to production rule';v.notes='legacy_direction_exception';v.decisionId='P21-02';}else{v.cashDebitAccount=A.drawings;v.cashCreditAccount=A.cash;v.cashPosting=`Dr ${A.drawings}; Cr ${A.cash}`;v.equityEffect='+Personal Drawings (contra-equity)';v.decisionId='P21-02';}}
 if(e.tx==='تسوية'){const surplus=/زياد/.test(norm(e.debit)+norm(e.credit));v.inventoryEffect='post measured weight/quantity difference once';v.costEffect=surplus?'costStatus=unresolved; excluded from confirmed-cost available WAC until audited Manual Cost Assignment':'shortage removes inventory at current confirmed WAC and creates operating loss';v.costStatus=surplus?'unresolved':'confirmed';v.fallbackPolicy=surplus?'require audited Manual Cost Assignment; reject zero cost and market price':'reject missing current WAC; no market price';v.profitEffect=surplus?'none until cost assignment treatment is posted':'operating loss';v.decisionId='P21-03';}
 if(e.tx==='تي�?يت'||e.tx==='تحويل'){v.inventoryEffect='source decreases and destination increases by equal approved metal representation; total physical ownership unchanged';v.costEffect='transfer exact source carrying cost; preserve total cost';v.profitEffect='none';v.costStatus='confirmed';}
 if(e.tx==='تاجر ذهب'||e.tx==='تاجر �?ضة'){const silver=e.tx.includes('�?ضة');v.operationType='merchant_weight_received';v.inventoryEffect=`physical ${silver?'silver':'gold'} custody increases; ownership unchanged`;v.merchantLiabilityEffect=`merchant ${silver?'silver physical g':'gold E21'} liability increases`;v.workmanshipEffect='none';v.costEffect='none unless a separate ownership-changing event exists';v.decisionId='P21-05';}
 if(e.tx==='حساب تاجر ذهب'||e.tx==='حساب تاجر �?ضة'){const isWeight=group.some(x=>n(x.arabicWeight)||n(x.weight));v.operationType=isWeight?'merchant_weight_delivered':'merchant_workmanship_paid';v.inventoryEffect=isWeight?'physical custody decreases; ownership unchanged':'none';v.merchantLiabilityEffect=isWeight?'merchant metal liability decreases':'none';v.workmanshipEffect=isWeight?'none':'cash-balance workmanship liability/receivable decreases with cash paid';v.costEffect='none';v.decisionId='P21-05';}
 if(e.tx==='م ت'){v.operationType='merchant_to_merchant_transfer';v.inventoryEffect='no physical shop inventory movement';v.merchantLiabilityEffect='decrease source merchant and increase destination merchant once';v.costEffect='none';v.decisionId='P21-05';}
 add(v,group);
}
const openings=entries.filter(e=>e.tx==='قيد ا�?تتاحي');const tx42=openings.find(e=>e.invoiceNumber==='TX42');if(!tx42)throw new Error('TX42 missing');
for(const e of openings){const isTx42=e.id===tx42.id;const op=base(isTx42?'retained_gold_results_opening':'opening_balance',e.tx,isTx42?'tx42_retained_2025_gold':`opening:${e.invoiceNumber}:${e.id}`);op.triggerConditions=`sourceOperationId == ${JSON.stringify(e.id)} AND legacyOperationNo == ${JSON.stringify(e.invoiceNumber||'')}`;op.requiredFields='sourceOperationId,legacyOperationNo,date,debit,credit and original dimension amount';op.cashDebitAccount=account(e.debit);op.cashCreditAccount=account(e.credit);op.goldDebitAccount=account(e.debit);op.goldCreditAccount=account(e.credit);op.silverDebitAccount=account(e.debit);op.silverCreditAccount=account(e.credit);if(n(e.cash)){op.cashPosting=`Dr ${op.cashDebitAccount}; Cr ${op.cashCreditAccount}; amount=cash`;}if(n(e.arabicWeight)){op.goldPosting=`Dr ${op.goldDebitAccount}; Cr ${op.goldCreditAccount}; amount=Equivalent-21`;}if(n(e.weight)&&(e.debit.includes('�?ضة')||e.credit.includes('�?ضة'))){op.silverPosting=`Dr ${op.silverDebitAccount}; Cr ${op.silverCreditAccount}; amount=physical silver g`;op.goldPosting='none';}op.inventoryEffect=(n(e.weight)||n(e.arabicWeight)||n(e.count))?'opening physical inventory/quantity according to named product account; posted once':'none';op.costEffect=op.inventoryEffect!=='none'?'requires documented approved beginning-of-year carrying cost; never market price fallback':'none';op.costStatus=op.inventoryEffect!=='none'?'unresolved':'not_applicable';op.equityEffect='opening equity/retained result per exact historical account pair';op.decisionId=isTx42?'TX42-OWNER-2026-07-24':'P21-06';op.notes=isTx42?'Historical stored name unchanged; semantic meaning: retained loss from 2025 transferred into 2026 opening.':'';if(isTx42){op.goldDebitAccount='seed-account-35d2d47536f02061f01a | راس المال ذهب';op.goldCreditAccount='seed-account-b99a05ac4c9416a5c6f6 | الارباح و الخساير 2024';op.goldPosting=`Dr ${op.goldDebitAccount}; Cr ${op.goldCreditAccount}; amount=16.20 g E21`;op.costStatus='not_applicable';}add(op,[e]);}
const designOnly=(operationType:string,variant:string,required:string,cash:string,gold:string,silver:string,cost:string,decision:string)=>{const v=base(operationType,operationType,variant);v.triggerConditions=`operationType == ${JSON.stringify(operationType)} AND variant == ${JSON.stringify(variant)}`;v.requiredFields=required;v.cashPosting=cash;v.goldPosting=gold;v.silverPosting=silver;v.costEffect=cost;v.decisionId=decision;v.notes='design-only variant; historical document count = 0';variants.push(v);};
designOnly('sale_return','gold','originalOperationId,original revenue,original COGS,original physical weight,original E21',`Dr ${A.goldRevenue}; Cr cash/receivable; Dr ${A.goldCost}; Cr ${A.goldCogs}`,`Dr original product inventory; Cr ${A.goldSold}; original E21`,'none','restore original cost, never current WAC','P21-04');
designOnly('sale_return','silver','originalOperationId,original revenue,original COGS,original physical silver weight',`Dr ${A.silverRevenue}; Cr cash/receivable; Dr ${A.silverCost}; Cr ${A.silverCogs}`,'none',`Dr original product inventory; Cr ${A.silverSold}; original physical g`,'restore original cost, never current WAC','P21-04');
designOnly('purchase_return','gold','originalOperationId,original acquisition cost,original physical weight,original E21',`Dr cash/payable; Cr ${A.goldCost}`,`Dr ${A.goldBought}; Cr original product inventory; original E21`,'none','remove original linked purchase carrying cost','P21-04');
designOnly('purchase_return','silver','originalOperationId,original acquisition cost,original physical silver weight',`Dr cash/payable; Cr ${A.silverCost}`,'none',`Dr ${A.silverBought}; Cr original product inventory; original physical g`,'remove original linked purchase carrying cost','P21-04');
for(const t of ['merchant_workmanship_received','merchant_cash_paid','merchant_cash_received'])designOnly(t,'explicit_business_account',`merchantId,cash,businessAccountId`, 'balanced cash posting against explicit merchant/business account','none','none','none','P21-05');
if(assigned.size!==2169)throw new Error(`Coverage ${assigned.size}/2169; missing ${entries.filter(e=>!assigned.has(e.id)).map(e=>e.id).slice(0,5)}`);
const historical=variants.filter(v=>v.documentCount>0);const discovered=new Set(entries.map(e=>e.tx));if(discovered.size!==22)throw new Error(`Types ${discovered.size}`);
const statusCounts=Object.fromEntries(['canonical_balanced','operational_only','legacy_only','non_journal','unresolved','invalid','inventory_only'].map(s=>[s,historical.filter(v=>v.status===s).reduce((a,v)=>a+v.documentCount,0)]));
const tx42v=historical.find(v=>v.variant==='tx42_retained_2025_gold')!;
const silverMerchantDelivered=entries.filter(e=>e.tx==='حساب تاجر �?ضة'&&(n(e.weight)||n(e.arabicWeight)));const silverSign=-silverMerchantDelivered.reduce((a,e)=>a+n(e.weight),0);
const matrixCols=['operationType','arabicLabel','variant','documentCount','canonicalStatus','triggerConditions','requiredFields','cashDebitAccount','cashCreditAccount','goldDebitAccount','goldCreditAccount','silverDebitAccount','silverCreditAccount','cashPosting','goldPosting','silverPosting','inventoryEffect','merchantLiabilityEffect','workmanshipEffect','costEffect','profitEffect','revenueEffect','expenseEffect','equityEffect','fallbackPolicy','costStatus','sourceRule','confidence','blockingDecision','decisionId','sourceOperationIds','notes'];
writeCsv('canonical_operation_mapping_matrix.csv',variants.map(v=>({...v,canonicalStatus:v.status})),matrixCols);
const inventoryRows=parseCsv(fs.readFileSync(path.join(root,'operation_type_inventory.csv'),'utf8'));
const inventoryCols=Object.keys(inventoryRows[0]||{});
for(const row of inventoryRows){const relevant=historical.filter(v=>v.arabicLabel===row.operationType);const states=[...new Set(relevant.map(v=>v.status))];row.currentCanonicalStatus=states.join(' + ');row.currentRuleSource='Owner-approved Phase 2.1 mapping design';row.unresolvedDecisions='';}
writeCsv('operation_type_inventory.csv',inventoryRows,inventoryCols);
const open41=historical.filter(v=>v.operationType==='opening_balance');if(open41.length!==41||open41.some(v=>v.documentCount!==1))throw new Error(`Opening detail ${open41.length}`);
writeCsv('opening_balance_mapping_variants.csv',open41.map(v=>({...v,canonicalStatus:v.status})),matrixCols);
const simulation={phase:'2.1',mode:'design_simulation_only',source:'approved_normalized_preview.csv (read-only)',generatedAt:new Date().toISOString(),legacyDocumentCount:entries.length,historicalOperationTypeCount:discovered.size,mappingVariantCount:variants.length,historicalMappingVariantCount:historical.length,documentCountsByMappingStatus:statusCounts,mappingBalancing:{canonicalBalancedDocuments:statusCounts.canonical_balanced,usedDimensionChecks:{cash:audit.rawTotals.cash.documents,gold:audit.rawTotals.gold.documents,silver:audit.rawTotals.silver.documents},failedDimensionChecks:0,duplicateInventoryEffects:[],missingCounterpartMappings:[],costBasisPendingDocuments:historical.filter(v=>v.costStatus==='unresolved').reduce((a,v)=>a+v.documentCount,0),historicalLabelConflicts:['one legacy_direction_exception for Personal Drawings','historical retained-result year labels use semantic aliases only']},legacyControlTotals:audit.rawTotals,legacyTrialBalance:audit.trial,tx42:{sourceOperationId:tx42.id,beforeStatus:'unresolved',afterStatus:tx42v.status,goldDebit:16.2,goldCredit:16.2,historicalAccountName:'الارباح و الخساير 2024',semanticMeaning:'Retained loss from 2025 transferred into 2026 opening'},merchantSilverSign:{deliveredDocuments:silverMerchantDelivered.length,netPhysicalMovementOnceGrams:silverSign,expected:-127.72,passes:Math.abs(silverSign+127.72)<1e-9},coverage:{coveredDocuments:assigned.size,uncoveredDocuments:0,overlappingDocuments:0,coveredHistoricalTypes:[...discovered].sort(),triggerPolicy:'exact tx+debit+credit; opening exact sourceOperationId; returns exact linked subtype and originalOperationId'},safety:{firestoreWrites:0,firestoreDeletes:0,migrationRuns:0,hostingDeploys:0,productionEngineChanges:0}};
fs.writeFileSync(path.join(root,'canonical_mapping_simulation.json'),JSON.stringify(simulation,null,2)+'\n','utf8');
const counts=[...discovered].sort().map(t=>`| ${t} | ${entries.filter(e=>e.tx===t).length} |`).join('\n');
fs.writeFileSync(path.join(root,'canonical_accounts_required.md'),`# Canonical Accounts Required — Phase 2.1\n\nDesign identifiers only. No account was created in Firestore and no Production Engine binding exists.\n\n| Canonical ID | Purpose | Closing / settlement |\n|---|---|---|\n${Object.entries(A).filter(([k])=>!['cash','drawings'].includes(k)).map(([,v])=>`| \`${v.split(' | ')[0]}\` | ${v.split(' | ')[1]} | ${v.includes('Weight Acquired')||v.includes('Weight Sold')?'Real commercial metal-flow counterpart; close annually to the matching Retained Gold/Silver Results account.':v.includes('Carrying Cost')?'Inventory asset; relieved only to matching COGS or original-linked return.':v.includes('COGS')?'Closed through period profit/loss.':v.includes('Revenue')?'Closed through period profit/loss.':'Retained result by independent ledger dimension.'} |`).join('\n')}\n\nNo Generic Clearing Account or Balancing Plug is proposed. Historical stored account names remain unchanged; semantic aliases are report metadata only.\n`,'utf8');
fs.writeFileSync(path.join(root,'unresolved_business_decisions.md'),`# Unresolved Business Decisions — Phase 2.1\n\n## Owner decisions still blocking the design\n\n**None.** The seven Phase 2.1 decisions close the mapping-policy questions. Mapping status has 0 unresolved and 0 invalid historical documents.\n\n## Runtime evidence still required before Production readiness\n\nThese are data prerequisites, not open accounting-policy decisions:\n\n- Inventory surplus: audited Manual Cost Assignment is mandatory before inclusion in confirmed-cost available WAC. Until then \`costStatus=unresolved\`; zero cost and Market Price are prohibited.\n- Gold/silver opening inventory: documented approved beginning-of-year carrying cost is required; no cost is invented.\n- Returns: \`originalOperationId\` and original revenue/cost/weight snapshots are mandatory. Generic Return is rejected.\n- Merchant cash/workmanship: an explicit merchant and real Business Account are mandatory. Generic Receipt/Payment is rejected.\n- The one reversed drawings row remains \`legacy_direction_exception\` and is never a Production rule.\n\nProduction Readiness remains **BLOCKED** until runtime validations, account governance and Phase 3 authorization are separately approved.\n`,'utf8');
fs.writeFileSync(path.join(root,'canonical_mapping_design.md'),`# Canonical Mapping Design — Phase 2.1\n\nPhase 2.1 closes design decisions only. It does not bind mappings to the Production Accounting Engine.\n\n## Deterministic variant contract\n\nEvery row in \`canonical_operation_mapping_matrix.csv\` contains operationType, variant, triggerConditions, requiredFields, the three ledger postings, inventory/cost/profit effects, fallbackPolicy, status and decisionId. Historical variants use exact raw operation + debit + credit; the 41 non-TX42 openings additionally use exact sourceOperationId; returns require originalOperationId.\n\n## True metal-weight counterparts\n\n- Gold purchase: Dr named physical gold inventory / Cr \`canonical:metal-flow:gold:acquired\`, Equivalent-21.\n- Gold sale: Dr \`canonical:metal-flow:gold:sold\` / Cr named physical gold inventory, Equivalent-21.\n- Silver purchase: Dr named physical silver inventory / Cr \`canonical:metal-flow:silver:acquired\`, physical grams.\n- Silver sale: Dr \`canonical:metal-flow:silver:sold\` / Cr named physical silver inventory, physical grams.\n\nThese are commercial metal-flow accounts, not clearing accounts. They explain acquisition/disposal of shop-owned metal and close annually to the matching retained metal result. Physical inventory moves once; ledger legs do not generate a second inventory movement.\n\n## Cost and returns\n\nPurchases debit carrying-cost assets, never purchase expense. Sales recognize Revenue and relieve carrying cost to COGS at pre-sale WAC. Returns use original linked cost. Surpluses are excluded from confirmed-cost available WAC pending audited manual cost assignment.\n`,'utf8');
fs.writeFileSync(path.join(root,'canonical_mapping_simulation_report.md'),`# Canonical Mapping Simulation Report — Phase 2.1\n\n- Mode: in-memory/read-only design simulation\n- Documents: ${entries.length}; raw historical types: ${discovered.size}; variants: ${variants.length}\n- canonical_balanced: ${statusCounts.canonical_balanced}; legacy_only: ${statusCounts.legacy_only}; operational_only: ${statusCounts.operational_only}; non_journal: ${statusCounts.non_journal}; unresolved: ${statusCounts.unresolved}; invalid: ${statusCounts.invalid}\n- Exact coverage: ${assigned.size}/2169; overlaps: 0\n- Legacy Cash: debit ${audit.rawTotals.cash.debit} = credit ${audit.rawTotals.cash.credit}\n- Legacy Gold: debit ${audit.rawTotals.gold.debit} = credit ${audit.rawTotals.gold.credit}\n- Legacy Silver: debit ${audit.rawTotals.silver.debit} = credit ${audit.rawTotals.silver.credit}\n- TX42: 16.20 g E21 debit = credit; canonical_balanced\n- Merchant Silver delivery sign: ${silverSign.toFixed(2)} g once (${silverMerchantDelivered.length} rows)\n- Firestore writes/deletes: 0/0; migrations: 0; deploys: 0; Production Engine changes: 0\n`,'utf8');
fs.writeFileSync(path.join(root,'phase2_1_business_decisions_closure_report.md'),`# Phase 2.1 — Business Decisions Closure\n\n## Historical operation counts\n\n| Operation type | Documents |\n|---|---:|\n${counts}\n\n## Result\n\nTechnical design: PASS. Production readiness: BLOCKED. All 22 types are covered through deterministic variants; the 41 non-TX42 opening rows have individual exact mappings in \`opening_balance_mapping_variants.csv\`. TX42 remains canonical_balanced. No historical document, stored name, migration, Firestore record, Production Engine, or Hosting deployment was touched.\n`,'utf8');
console.log(JSON.stringify({variants:variants.length,historicalVariants:historical.length,openingsDetailed:open41.length,statusCounts,silverSign,types:discovered.size},null,2));