import type { Account } from './types';

export const SEED_ACCOUNTS = [
  { name: "الخزنة", mainType: "اصول", subType: "النقدية بالخزنة", balanceNature: "جنية مصري", type: 'cash', is_inventory: false, karat: null, metal: null },
  { name: "خاتم حريمي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "خاتم اطفال", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "حلق حريمي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "حلق اطفال", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "حلق مكرونة", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "تونز", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "دبلة", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "محبس", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "اسورة و انسيال", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "سلسلة و تعليق", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "غويش كيمك", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "بريمة", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "خاتم عربي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "حلق عربي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "غويش عربي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "سلسلة عربي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_product', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "كسر افرنجي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_raw', is_inventory: true, karat: '18', metal: 'gold' },
  { name: "كسر عربي", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_raw', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "جنية", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_direct', is_inventory: true, karat: '21', metal: 'gold' },
  { name: "سبيكة", mainType: "اصول", subType: "مخزون ذهب", balanceNature: "جرام ذهب", type: 'gold_direct', is_inventory: true, karat: '24', metal: 'gold' },
  { name: "خاتم فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "خاتم حريمي فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "دبلة فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "سلسلة رجالي فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "سلسلة حريمي فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "ميدالية فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "قفل فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "كسر فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "سبيكة فضة", mainType: "اصول", subType: "مخزون فضة", balanceNature: "جرام فضة", type: 'silver', is_inventory: true, karat: null, metal: 'silver' },
  { name: "دبلة تنجستين", mainType: "اصول", subType: "مخزون ملحقات اضافية", balanceNature: "قطعة", type: 'accessory', is_inventory: true, karat: null, metal: null },
  { name: "حلق طبي", mainType: "اصول", subType: "مخزون ملحقات اضافية", balanceNature: "قطعة", type: 'accessory', is_inventory: true, karat: null, metal: null },
  { name: "سيليكون", mainType: "اصول", subType: "مخزون ملحقات اضافية", balanceNature: "قطعة", type: 'accessory', is_inventory: true, karat: null, metal: null },
  { name: "مكنة عد نقدية", mainType: "اصول", subType: "اصول ثابتة", canonicalMainType: 'assets', canonicalSubType: 'fixed_asset', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "لابتوب", mainType: "اصول", subType: "اصول ثابتة", canonicalMainType: 'assets', canonicalSubType: 'fixed_asset', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "تليفون ارضي", mainType: "اصول", subType: "اصول ثابتة", canonicalMainType: 'assets', canonicalSubType: 'fixed_asset', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "شروق حبشي", mainType: "اصول", subType: "ذمم مدينة", canonicalMainType: 'assets', canonicalSubType: 'customer', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "علا حسن", mainType: "اصول", subType: "ذمم مدينة", canonicalMainType: 'assets', canonicalSubType: 'customer', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "محمد السيد", mainType: "خصوم", subType: "تجار ذهب", canonicalMainType: 'liabilities', canonicalSubType: 'merchant_gold', merchantDirection: 'payable', balanceNature: "جرام ذهب", type: 'merchant', is_inventory: false, karat: null, metal: 'gold' },
  { name: "الصافي", mainType: "خصوم", subType: "تجار ذهب", canonicalMainType: 'liabilities', canonicalSubType: 'merchant_gold', merchantDirection: 'payable', balanceNature: "جرام ذهب", type: 'merchant', is_inventory: false, karat: null, metal: 'gold' },
  { name: "علاء صالح", mainType: "خصوم", subType: "تجار ذهب", canonicalMainType: 'liabilities', canonicalSubType: 'merchant_gold', merchantDirection: 'payable', balanceNature: "جرام ذهب", type: 'merchant', is_inventory: false, karat: null, metal: 'gold' },
  { name: "خالد حميدو", mainType: "خصوم", subType: "تجار ذهب", canonicalMainType: 'liabilities', canonicalSubType: 'merchant_gold', merchantDirection: 'payable', balanceNature: "جرام ذهب", type: 'merchant', is_inventory: false, karat: null, metal: 'gold' },
  { name: "سمير ناشد", mainType: "خصوم", subType: "تجار فضة", canonicalMainType: 'liabilities', canonicalSubType: 'merchant_silver', merchantDirection: 'payable', balanceNature: "جرام فضة", type: 'merchant', is_inventory: false, karat: null, metal: 'silver' },
  { name: "الاء ياسر", mainType: "خصوم", subType: "ذمم دائنة", canonicalMainType: 'liabilities', canonicalSubType: 'other_due', merchantDirection: 'payable', balanceNature: "جرام ذهب", type: 'other', is_inventory: false, karat: null, metal: 'gold' },
  { name: "دينا", mainType: "خصوم", subType: "ذمم دائنة", canonicalMainType: 'liabilities', canonicalSubType: 'customer', balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "راس المال ذهب", mainType: "حقوق ملكية", subType: "راس المال", balanceNature: "جرام ذهب", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "راس المال فضة", mainType: "حقوق ملكية", subType: "راس المال", balanceNature: "جرام فضة", type: 'other', is_inventory: false, karat: null, metal: 'silver' },
  { name: "راس المال ملحقات", mainType: "حقوق ملكية", subType: "راس المال", balanceNature: "قطعة", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "راس المال نقدا", mainType: "حقوق ملكية", subType: "راس المال", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "المسحوبات", mainType: "حقوق ملكية", subType: "مسحوبات", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "الارباح و الخساير 2024", mainType: "حقوق ملكية", subType: "الارباح و الخساير", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "الارباح و الخساير 2024 ذهب", mainType: "حقوق ملكية", subType: "الارباح و الخساير", balanceNature: "جرام ذهب", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "الارباح و الخساير 2024 فضة", mainType: "حقوق ملكية", subType: "الارباح و الخساير", balanceNature: "جرام فضة", type: 'other', is_inventory: false, karat: null, metal: 'silver' },
  { name: "تصليح", mainType: "ايرادات", subType: "ايرادات اخري", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "زيادة-الخزنة", mainType: "ايرادات", subType: "تسوية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "زيادة-الذهب", mainType: "ايرادات", subType: "تسوية", balanceNature: "جرام ذهب", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "تيفيت الكسر", mainType: "مصروفات", subType: "مصاريف تشغيلية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "نقل و توصيل", mainType: "مصروفات", subType: "مصاريف تشغيلية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "انبوبة", mainType: "مصروفات", subType: "مصاريف تشغيلية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "محمد ياسر", mainType: "مصروفات", subType: "مصاريف تشغيلية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "مكافئات", mainType: "مصروفات", subType: "مصاريف تشغيلية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "كهرباء", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "مياة", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "انترنت و ارضي", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "تامينات", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "كافيتريا", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "منظفات", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "فرشة سلك", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "تصليحات", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "الذكاة", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "الصدقات", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "عجز-الخزنة", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "عجز-الذهب", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جرام ذهب", type: 'other', is_inventory: false, karat: null, metal: null },
  { name: "نثريات", mainType: "مصروفات", subType: "مصاريف ادارية عمومية", balanceNature: "جنية مصري", type: 'other', is_inventory: false, karat: null, metal: null }
] satisfies Array<Omit<Account, 'id' | 'userId'>>;

export const SEED_RULES = [
  { debit: "الخزنة", credit: "تصليح", tx: "ايرادات اخري", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "كسر افرنجي", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "كسر عربي", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "حلق عربي", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "سبيكة", tx: "بيع ذهب", karat: 24, multiplier: 1.142857143, category: "المبيعات" },
  { debit: "الخزنة", credit: "حلق اطفال", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "خاتم حريمي", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "سلسلة و تعليق", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "خاتم عربي", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "حلق مكرونة", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "دبلة", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "تونز", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "جنية", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "خاتم اطفال", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "بريمة", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "اسورة و انسيال", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "غويش عربي", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "حلق حريمي", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "غويش كيمك", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "سلسلة عربي", tx: "بيع ذهب", karat: 21, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "محبس", tx: "بيع ذهب", karat: 18, multiplier: 0.857142857, category: "المبيعات" },
  { debit: "الخزنة", credit: "سبيكة فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "دبلة فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "خاتم فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "خاتم حريمي فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "قفل فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "سلسلة رجالي فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "سلسلة حريمي فضة", tx: "بيع فضة", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "دبلة تنجستين", tx: "بيع ملحقات", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "حلق طبي", tx: "بيع ملحقات", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "الخزنة", credit: "سيليكون", tx: "بيع ملحقات", karat: null, multiplier: 1, category: "المبيعات" },
  { debit: "حلق حريمي", credit: "محمد السيد", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "حلق مكرونة", credit: "محمد السيد", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "خاتم حريمي", credit: "محمد السيد", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "دبلة", credit: "محمد السيد", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "سلسلة و تعليق", credit: "محمد السيد", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "سلسلة و تعليق", credit: "خالد حميدو", tx: "تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "دبلة فضة", credit: "سمير ناشد", tx: "تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "سلسلة حريمي فضة", credit: "سمير ناشد", tx: "تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "خاتم حريمي", credit: "تونز", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر افرنجي", credit: "خاتم حريمي", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر افرنجي", credit: "حلق اطفال", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر افرنجي", credit: "دبلة", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر افرنجي", credit: "اسورة و انسيال", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر افرنجي", credit: "سلسلة و تعليق", tx: "تحويل", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "كسر عربي", credit: "حلق عربي", tx: "تحويل", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "كسر عربي", credit: "خاتم عربي", tx: "تحويل", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "كسر عربي", credit: "غويش عربي", tx: "تحويل", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "الخزنة", credit: "زيادة-الخزنة", tx: "تسوية", karat: null, multiplier: 1, category: "تسويات" },
  { debit: "حلق حريمي", credit: "حلق اطفال", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "سلسلة و تعليق", credit: "زيادة-الذهب", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الخزنة", credit: "الخزنة", tx: "تسوية", karat: null, multiplier: 1, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "كسر عربي", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "خاتم اطفال", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "بريمة", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "اسورة و انسيال", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "محبس", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "دبلة", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "سلسلة عربي", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "كسر افرنجي", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "عجز-الذهب", credit: "حلق مكرونة", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "غويش عربي", credit: "زيادة-الذهب", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "كسر افرنجي", credit: "زيادة-الذهب", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "كسر عربي", credit: "زيادة-الذهب", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "اسورة و انسيال", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "بريمة", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "تونز", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "حلق اطفال", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "حلق حريمي", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "حلق عربي", credit: "كسر عربي", tx: "تيفيت", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "حلق مكرونة", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "خاتم اطفال", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "خاتم حريمي", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "خاتم عربي", credit: "كسر عربي", tx: "تيفيت", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "دبلة", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "سلسلة عربي", credit: "كسر عربي", tx: "تيفيت", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "سلسلة و تعليق", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "غويش عربي", credit: "كسر عربي", tx: "تيفيت", karat: 21, multiplier: 1, category: "العمليات الداخلية" },
  { debit: "غويش كيمك", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "محبس", credit: "كسر افرنجي", tx: "تيفيت", karat: 18, multiplier: 0.857142857, category: "العمليات الداخلية" },
  { debit: "الصافي", credit: "كسر عربي", tx: "حساب تاجر ذهب", karat: 21, multiplier: 1, category: "التجار" },
  { debit: "الصافي", credit: "كسر افرنجي", tx: "حساب تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "خالد حميدو", credit: "الخزنة", tx: "حساب تاجر ذهب", karat: null, multiplier: 1, category: "التجار" },
  { debit: "خالد حميدو", credit: "كسر افرنجي", tx: "حساب تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "علاء صالح", credit: "الخزنة", tx: "حساب تاجر ذهب", karat: null, multiplier: 1, category: "التجار" },
  { debit: "محمد السيد", credit: "الخزنة", tx: "حساب تاجر ذهب", karat: null, multiplier: 1, category: "التجار" },
  { debit: "محمد السيد", credit: "كسر افرنجي", tx: "حساب تاجر ذهب", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "سمير ناشد", credit: "كسر فضة", tx: "حساب تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "سمير ناشد", credit: "الخزنة", tx: "حساب تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "محمد السيد", credit: "الصافي", tx: "حوالة", karat: 18, multiplier: 0.857142857, category: "التجار" },
  { debit: "شروق حبشي", credit: "الخزنة", tx: "دفع لعميل", karat: null, multiplier: 1, category: "العملاء" },
  { debit: "علا حسن", credit: "الخزنة", tx: "دفع لعميل", karat: null, multiplier: 1, category: "العملاء" },
  { debit: "مكنة عد نقدية", credit: "الخزنة", tx: "شراء اصل", karat: null, multiplier: 1, category: "المشتريات" },
  { debit: "جنية", credit: "الخزنة", tx: "شراء ذهب", karat: 21, multiplier: 1, category: "المشتريات" },
  { debit: "سبيكة", credit: "الخزنة", tx: "شراء ذهب", karat: 24, multiplier: 1.142857143, category: "المشتريات" },
  { debit: "كسر افرنجي", credit: "الخزنة", tx: "شراء ذهب", karat: 18, multiplier: 0.857142857, category: "المشتريات" },
  { debit: "كسر عربي", credit: "الخزنة", tx: "شراء ذهب", karat: 21, multiplier: 1, category: "المشتريات" },
  { debit: "سبيكة فضة", credit: "الخزنة", tx: "شراء فضة", karat: null, multiplier: 1, category: "المشتريات" },
  { debit: "كسر فضة", credit: "الخزنة", tx: "شراء فضة", karat: null, multiplier: 1, category: "المشتريات" },
  { debit: "الخزنة", credit: "دينا", tx: "قبض من عميل", karat: null, multiplier: 1, category: "العملاء" },
  { debit: "الخزنة", credit: "شروق حبشي", tx: "قبض من عميل", karat: null, multiplier: 1, category: "العملاء" },
  { debit: "الذكاة", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "الصدقات", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "انترنت و ارضي", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "تامينات", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "تصليحات", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "فرشة سلك", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "كافيتريا", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "كهرباء", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "منظفات", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "مياة", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "نثريات", credit: "الخزنة", tx: "م ا ع", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "انبوبة", credit: "الخزنة", tx: "م ت", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "تيفيت الكسر", credit: "الخزنة", tx: "م ت", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "محمد ياسر", credit: "الخزنة", tx: "م ت", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "مكافئات", credit: "الخزنة", tx: "م ت", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "نقل و توصيل", credit: "الخزنة", tx: "م ت", karat: null, multiplier: 1, category: "المصاريف" },
  { debit: "الخزنة", credit: "المسحوبات", tx: "مسحوبات", karat: null, multiplier: 1, category: "المسحوبات" },
  { debit: "المسحوبات", credit: "الخزنة", tx: "مسحوبات", karat: null, multiplier: 1, category: "المسحوبات" },
  // Approved from the local CSV resolution report. These are exact historical
  // combinations only; they do not alter or normalize the raw source rows.
  { debit: "حلق عربي", credit: "زيادة-الذهب", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "دبلة", credit: "زيادة-الذهب", tx: "تسوية", karat: 18, multiplier: 0.857142857, category: "تسويات" },
  { debit: "خاتم عربي", credit: "زيادة-الذهب", tx: "تسوية", karat: 21, multiplier: 1, category: "تسويات" },
  { debit: "خاتم فضة", credit: "سمير ناشد", tx: "تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "خاتم حريمي فضة", credit: "سمير ناشد", tx: "تاجر فضة", karat: null, multiplier: 1, category: "التجار" },
  { debit: "دبلة تنجستين", credit: "الخزنة", tx: "شراء ملحقات", karat: null, multiplier: 1, category: "المشتريات" },
  { debit: "راس المال نقدا", credit: "محمد السيد", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "قفل فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "دبلة فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "غويش كيمك", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "الارباح و الخساير 2024 فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "الخزنة", credit: "راس المال نقدا", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "راس المال فضة", credit: "سمير ناشد", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "كسر عربي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "سيليكون", credit: "راس المال ملحقات", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "اسورة و انسيال", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "راس المال ذهب", credit: "الصافي", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "راس المال ذهب", credit: "الاء ياسر", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "حلق حريمي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "غويش عربي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "دبلة تنجستين", credit: "راس المال ملحقات", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "حلق طبي", credit: "راس المال ملحقات", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "تونز", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "راس المال ذهب", credit: "محمد السيد", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "بريمة", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "خاتم عربي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "راس المال نقدا", credit: "علاء صالح", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "خاتم اطفال", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "حلق اطفال", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "سبيكة", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 24, multiplier: 1.142857143, category: "قيود افتتاحية" },
  { debit: "محبس", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "حلق مكرونة", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "خاتم فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "سلسلة و تعليق", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "تليفون ارضي", credit: "راس المال نقدا", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "لابتوب", credit: "راس المال نقدا", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "سلسلة رجالي فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "خاتم حريمي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "راس المال ذهب", credit: "الارباح و الخساير 2024", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "خاتم حريمي فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "شروق حبشي", credit: "راس المال نقدا", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "حلق عربي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 21, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "دبلة", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "كسر افرنجي", credit: "راس المال ذهب", tx: "قيد افتتاحي", karat: 18, multiplier: 0.857142857, category: "قيود افتتاحية" },
  { debit: "كسر فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "الارباح و الخساير 2024", credit: "راس المال نقدا", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "سلسلة حريمي فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
  { debit: "ميدالية فضة", credit: "راس المال فضة", tx: "قيد افتتاحي", karat: null, multiplier: 1, category: "قيود افتتاحية" },
];
