import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Account, CanonicalAccountDefinition, TransactionRule } from '../../types';
const fake = vi.hoisted(() => ({ writes: [] as Array<{ id: string; data: Record<string, unknown> }>, existing: [] as TransactionRule[] }));
vi.mock('firebase/firestore', () => ({ collection: (_db: unknown, name: string) => ({ name }), query: (ref: unknown) => ref, where: () => ({}), doc: (_db: unknown, _collection: string, id: string) => ({ id }), serverTimestamp: () => 'timestamp', getDocs: async () => ({ docs: fake.existing.map(rule => ({ id: rule.id, data: () => rule })) }), runTransaction: async (_db: unknown, handler: (tx: { get: (ref: { id: string }) => Promise<{ exists: () => boolean }>; set: (ref: { id: string }, data: Record<string, unknown>) => void }) => Promise<void>) => handler({ get: async () => ({ exists: () => false }), set: (ref, data) => { fake.writes.push({ id: ref.id, data }); } }) }));
import { addAccountUse } from '../accountUseService';
const account: Account = { id: 'customer-2', name: 'Customer 2', mainType: 'assets', subType: 'customer', canonicalSubType: 'customer', balanceNature: 'debit', userId: 'u', type: 'other', metal: null, is_inventory: false };
const sourceAccount: Account = { ...account, id: 'customer', name: 'Customer' };
const cash: Account = { id: 'cash', name: 'Cash', mainType: 'assets', subType: 'cash', canonicalSubType: 'cash', balanceNature: 'debit', userId: 'u', type: 'cash', metal: null, is_inventory: false };
const candidate = { tx: 'Collection', side: 'credit' as const, counterpartName: cash.name, counterpartAccountId: 'cash', multiplier: 1, category: 'x' };
const provenRule: TransactionRule = { id: 'r1', tx: candidate.tx, debit: cash.name, credit: sourceAccount.name, debitAccountId: cash.id, creditAccountId: sourceAccount.id, category: 'x', userId: 'u', multiplier: 1 };
const historicalCanonical = { entityType: 'customer', isHistoricalOnly: true, classificationConflicts: [] } as CanonicalAccountDefinition;
const conflictingCanonical = { entityType: 'customer', isHistoricalOnly: false, classificationConflicts: ['conflict'] } as unknown as CanonicalAccountDefinition;
const operationalCanonical = { entityType: 'customer', isHistoricalOnly: false, classificationConflicts: [] } as unknown as CanonicalAccountDefinition;
beforeEach(() => { fake.writes.length = 0; fake.existing = []; });
describe('isolated account use persistence', () => {
  const args = () => ({ firestore: {} as never, userId: 'u', account, canonical: operationalCanonical, candidate, rules: [provenRule], accounts: [account, sourceAccount, cash] });
  it('writes one independent rule with explicit managed identity', async () => { const result = await addAccountUse(args()); expect(fake.writes).toHaveLength(1); expect(fake.writes[0].data).toMatchObject({ tx: 'Collection', creditAccountId: 'customer-2', debitAccountId: 'cash' }); expect(result.id).toBe(fake.writes[0].id); });
  it('rejects protected accounts and arbitrary candidates without writing', async () => { await expect(addAccountUse({ ...args(), account: cash })).rejects.toThrow(); await expect(addAccountUse({ ...args(), candidate: { ...candidate, counterpartAccountId: 'unknown' } })).rejects.toThrow(); expect(fake.writes).toHaveLength(0); });
  it('rejects canonical-only protected accounts before any write', async () => { fake.existing = [provenRule]; const before = [...fake.existing]; await expect(addAccountUse({ ...args(), canonical: historicalCanonical })).rejects.toThrow(); await expect(addAccountUse({ ...args(), canonical: conflictingCanonical })).rejects.toThrow(); expect(fake.writes).toHaveLength(0); expect(fake.existing).toEqual(before); });
  it('rejects duplicate rules without writing', async () => { fake.existing = [{ ...provenRule, credit: account.name, creditAccountId: account.id }]; await expect(addAccountUse(args())).rejects.toThrow(); expect(fake.writes).toHaveLength(0); });
});
